---
# tasks file for apache
 - name: Configure APACHE web server
   dnf:
     name: "{{ p }}"
     state: present

 - name: Start and Enable APACHE service
   service:
     name: "{{ s }}"
     state: started
     enabled: yes

 - name: Transfer webpage file
   template:
     src: web.j2
     dest: /var/www/html/index.html
   notify:
     - restart httpd

